### ISSUE TITLE
Depend on source-map-support v1.0

### ISSUE THREAD

**Issue by joebowbeer** [chocolateboy/babel-plugin-source-map-support#15]
It concerns me that source-map-support is not yet at 1.0: https://github.com/evanw/node-source-map-support/issues/223

Is there some way this excellent babel plugin can require a v1.0 package to perform the runtime mapping?

**Comment by chocolateboy** [comment]
> Is there some way this plugin can require a v1.0 package to perform the runtime mapping?

I'm not sure why you'd want this package to depend on a package that doesn't exist (yet), but either way, as mentioned in the [README](https://github.com/chocolateboy/babel-plugin-source-map-support#description) (and [here](https://github.com/chocolateboy/babel-plugin-source-map-support/issues/5#issuecomment-339400921)), this package doesn't depend on source-map-support. It's not even a peer dependency. It just enables it (if installed).

**Comment by joebowbeer** [comment]
I'm not sure you understand my concern.

Your README states:

> This is a Babel plugin which prepends the following statement to source files:
> 
> **import 'source-map-support/register';**
> 
> In conjunction with the source-map-support module, which _must be installed_ separately [...]

In every practical sense of the word, this package depends on a package that is currently at v0.5, has rarely been updated, and has a long issue list.
