### ISSUE TITLE
issue adding plugin to .babelrc

### ISSUE THREAD

**Issue by chalda** [chocolateboy/babel-plugin-source-map-support#5]
Hi there, trying to get your module working in attempt to fix some linenumber issues with mocha/babel.

getting the follow error:
```
Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

have the following .babelrc file where the plugin is being used:
```
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-object-rest-spread", "transform-decorators-legacy", "transform-class-properties"],
  "env": {
    "test": {
      "presets": ["es2015", "react", "stage-0"],
      "plugins": ["transform-object-rest-spread", "transform-decorators-legacy", "transform-class-properties", "rewire", "source-map-support"],
      "sourceMaps": "both"
    }
  }
}
```

and the test is run with babel-instanbul
```    "test:unit": "cross-env NODE_ENV=test babel-node node_modules/.bin/babel-istanbul cover --config=istanbul.json --dir coverage/unit node_modules/.bin/_mocha -- --require node_modules/ignore-styles 'client/**/*.spec.unit.js'",```

its possible the error is coming from babel-istanbul as that tool is somewhat outdated.

**Comment by chocolateboy** [comment]
>     Error: Cannot find module 'source-map-support/register'

You need to [install the source-map-support module](https://github.com/chocolateboy/babel-plugin-source-map-support#description):

> In conjunction with the [source-map-support](https://www.npmjs.com/package/source-map-support) module, **which must be installed separately**, this statement hooks into the v8 stack-trace API to translate call sites in the transpiled code back to their corresponding locations in the original code.

**Comment by chalda** [comment]
ahh musta missed it. my bad. why not install that module as a dependency or at least indicate it as a peer?

**Comment by chocolateboy** [comment]
Babel runs at compile time, and the dependency is needed at runtime. In practice you'll usually be bundling source-map-support locally for development and disabling it for production, in which case it would make sense to peer-depend on it, but that's just a convention, not an intrinsic requirement of this plugin.
