### ISSUE TITLE
Release a new version with stable Babel 7 support

### ISSUE THREAD

**Issue by deiga** [chocolateboy/babel-plugin-source-map-support#7]

**Comment by chocolateboy** [comment]
Why?

**Comment by chocolateboy** [comment]
If you're reporting a bug or requesting a feature, please provide [more information](http://xyproblem.info/).

If you just want to use this with Babel >= v7.0.0, then it should already work. This module's dependencies don't affect the version of Babel it works with. It should work with any version of Babel >=  [v7.0.0-beta.3](https://github.com/babel/babel/releases/tag/v7.0.0-beta.3) (which was released in October 2017).
